# Generated by Django 5.1.4 on 2024-12-17 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='query_to_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_departments', to='api.query'),
        ),
        migrations.AlterField(
            model_name='department',
            name='status',
            field=models.CharField(choices=[('ITSUPPORT', 'ITSUPPORT'), ('IT_TEAM', 'IT_TEAM'), ('HARDWARE SUPPORT', 'HARDWARE SUPPORT')], default='ITSUPPORT', max_length=20),
        ),
    ]
