# Generated by Django 5.1.4 on 2024-12-14 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otp',
            old_name='otp',
            new_name='email_otp',
        ),
        migrations.AddField(
            model_name='otp',
            name='phone_otp',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
