# Generated by Django 5.1.4 on 2024-12-21 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_query_options_remove_query_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queryhistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='queryhistory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
