# Generated by Django 5.1.4 on 2024-12-18 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_mobile_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='mobile_otp',
        ),
    ]
