# Generated by Django 5.1.4 on 2024-12-21 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='query',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.query'),
            preserve_default=False,
        ),
    ]
